[package]
name = "kvm-ioctls"
version = "0.1.0"
edition = "2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
kvm-bindings = { path = "../kvm-bindings", features = ["fam-wrappers"]}
vmm-sys-util = ">=0.10.0"